### ISSUE TITLE
Forward pass broken

### ISSUE THREAD

**Issue by bhack** [ralpguler/DenseReg#5]
In both the notebooks the forwadpass is broken on the default images:
`` blob.cpp:163] Check failed: data_ ``

**Comment by HaoyangWang** [comment]
Same!

**Comment by vitormcpedro** [comment]
Same here!

**Comment by sariyanidi** [comment]
Same here

**Comment by sariyanidi** [comment]
Ok I managed to make it work. Apparently @ralpguler answered this issue here: #3 

I had the issue when I compiled with the caffe that came along with DenseReg (i.e., in directory DeepLab-Context2). As @ralpguler mentions in the answer above, you should try to compile a fresh caffe from source but when you do this DenseReg will complain from the lack of interpolation layer. So you should temporarily modify the deploy.prototxt file by removing the interpolation layer and everything that comes after that. If you manage to parse this modified net, then you should put copy the interpolation layer from the caffe in DeepLab-Context2 into your fresh caffe from source. Here is what you should do (I expand @ralpguler's answer) to add the interp layer to your caffe.

Copy
* src/caffe/layers/interp_layer.cpp
* src/caffe/util/interp.cpp
* src/caffe/util/interp.cu
* include/caffe/util/interp.hpp
* include/caffe/layers/interp_layer.hpp
* include/caffe/common.cuh

Update caffe/proto/caffe.proto as follows:
* Add the line `optional InterpParameter interp_param = 149;` under the line `optional InnerProductParameter inner_product_param = 117;`
* Copy the code block 
`message InterpParameter {
  optional int32 height = 1 [default = 0]; // Height of output
  optional int32 width = 2 [default = 0]; // Width of output
  optional int32 zoom_factor = 3 [default = 1]; // zoom factor
  optional int32 shrink_factor = 4 [default = 1]; // shrink factor
  optional int32 pad_beg = 5 [default = 0]; // padding at begin of input
  optional int32 pad_end = 6 [default = 0]; // padding at end of input
}`
under the block 
`message InnerProductParameter {
…
}`

Then you should compile caffe from scratch, i.e., `make clean` and `make` and `make pycaffe`.
